/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
    id("com.android.library")
    id("aaosApps.buildLogic")
    id 'kotlin-android'
}

android{
    defaultConfig {
        minSdkVersion 30
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        testInstrumentationRunnerArguments clearPackageData: 'true', coverage: 'true'
    }
    namespace "com.android.car.media.testmediaapp"

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
        }

        androidTest{
            java.srcDirs += 'tests/instrumenttests/src'
        }

        test {
            java.srcDirs += 'tests/unittests/src'
        }
    }

    signingConfigs {
        unbundled {
            storeFile file(gradle.ext.unbundledCertPath)
            storePassword 'carapps'
            keyAlias 'carapps'
            keyPassword 'carapps'
        }
    }

    flavorDimensions "signingkey"
    productFlavors {
        unbundled {
            dimension "signingkey"
            signingConfig signingConfigs.unbundled
        }
    }

    kotlinOptions {
        jvmTarget = '11'
    }

    lintOptions {
        abortOnError false
    }

    testOptions {
        unitTests {
            includeAndroidResources = true
        }
        animationsDisabled = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    useLibrary 'android.test.runner'
    useLibrary 'android.test.base'
    useLibrary 'android.test.mock'
}

dependencies {
    implementation libs.androidx.appcompat
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.media
    implementation libs.androidx.media3.session
    // Keep commented out except for experimenting locally with the latest media3 source
    // See github.com/androidx/media?tab=readme-ov-file#locally
    // implementation project(':media3-lib-session')
    implementation libs.androidx.preference
    implementation libs.androidx.car.app

    testImplementation libs.androidx.junit
    testImplementation libs.junit
    testImplementation libs.robolectric
    testImplementation libs.mockito.core
    testImplementation libs.androidx.test.runner
    testImplementation libs.androidx.test.rules
}
